"""
Django settings for issueTracker project.

Generated by 'django-admin startproject' using Django 3.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load local environment variables from src/.env (preferred) and src/env (legacy).
# Force .env to win over stale shell variables from previous terminal sessions.
load_dotenv(BASE_DIR / '.env', override=False)
load_dotenv(BASE_DIR / 'env', override=False)

SECRET_KEY = os.environ.get('SECRET_KEY', default='dummy_key')
DEBUG = 'RENDER' not in os.environ
ALLOWED_HOSTS = ['*']

DATABASES = {
    "default": dj_database_url.config(
        default='postgresql://postgres:postgres@localhost:5432/issueTrackerDB',
        conn_health_checks=True,
    )
}

DATABASES['default']['CONN_MAX_AGE'] = 0

# Keep localhost as the configured host, but force IPv4 transport to avoid
# intermittent localhost/IPv6 reset issues on Windows + Docker.
if DATABASES['default'].get('HOST') in {'localhost', '::1'}:
    db_options = DATABASES['default'].setdefault('OPTIONS', {})
    db_options['hostaddr'] = '127.0.0.1'

if DEBUG:
    STORAGES = {
        "default": {
            "BACKEND": 'django.core.files.storage.FileSystemStorage'
        },
        "staticfiles": {
            "BACKEND": 'django.contrib.staticfiles.storage.StaticFilesStorage'
        },
    }
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
else:
    try:
        from google.oauth2 import service_account  # type: ignore[import-not-found]
    except ImportError:
        service_account = None

    STORAGES = {
        "default": {
            "BACKEND": 'storages.backends.gcloud.GoogleCloudStorage'
        },
        "staticfiles": {
            "BACKEND": 'storages.backends.gcloud.GoogleCloudStorage'
        },
    }

    GS_BUCKET_NAME = 'issue-tracker2026-media'
    MEDIA_URL = 'https://storage.googleapis.com/{}/'.format(GS_BUCKET_NAME)

    credentials_path = os.path.join(BASE_DIR, '../gcloud_credentials.json')
    if service_account is not None and os.path.exists(credentials_path):
        GS_CREDENTIALS = service_account.Credentials.from_service_account_file(credentials_path)

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.github',
    'issues.apps.IssuesConfig',
    'storages',
    'rest_framework',
    'corsheaders',
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

LOGIN_URL = '/'
LOGIN_REDIRECT_URL = '/issues/'
LOGOUT_REDIRECT_URL = '/'

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:8000",
    "https://issuetracker-ff8u.onrender.com",
    "https://editor.swagger.io",
    "https://issuetracker-frontend.vercel.app"
]
CORS_ALLOW_CREDENTIALS = True

# Allow Authorization header in CORS requests
from corsheaders.defaults import default_headers

CORS_ALLOW_HEADERS = list(default_headers) + [
    'authorization',
]

ROOT_URLCONF = 'issueTracker.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'issueTracker.wsgi.application'

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Madrid'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

if not DEBUG:
    STATICFILES_STORAGE = 'storages.backends.gcloud.GoogleCloudStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
