# Generated by Django 6.0.3 on 2026-04-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='name',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
