# Generated by Django 6.0.3 on 2026-04-14 19:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_attachment_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='watchers',
            field=models.ManyToManyField(blank=True, related_name='watched_issues', to=settings.AUTH_USER_MODEL),
        ),
    ]
