# Generated by Django 6.0.3 on 2026-04-14 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_issueactivity'),
        ('issues', '0006_issue_watchers'),
    ]

    operations = [
    ]
