# Generated by Django 6.0.3 on 2026-04-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0013_issue_remove_old_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='duedate',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='status',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        # Add slug WITHOUT unique so existing rows (all '') don't conflict
        migrations.AddField(
            model_name='status',
            name='slug',
            field=models.SlugField(blank=True, unique=False),
        ),
    ]
