# Generated by Django 6.0.3 on 2026-04-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0016_status_slug_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='priority',
            name='color',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='status',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
