# Generated by Django 6.0.3 on 2026-04-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0020_issuetype_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='severity',
            name='color',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
