# Generated by Django 6.0.3 on 2026-04-15 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0022_severity_colors_and_wishlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='duedate',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='duedate',
            name='date',
        ),
        migrations.AddField(
            model_name='duedate',
            name='before_or_after',
            field=models.CharField(blank=True, choices=[('before', 'Before'), ('after', 'After')], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='duedate',
            name='color',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='duedate',
            name='days_offset',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='duedate',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
