# Generated by Django 6.0.3 on 2026-04-24 11:28

import issues.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0024_duedate_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='api_key',
            field=models.CharField(default=issues.models.generate_api_key, editable=False, max_length=32),
        ),
    ]
